### ISSUE TITLE
Helpers for query processing (`elastic-helpers`?)

### ISSUE THREAD

**Issue by stephanbuys** [elastic-rs/elastic#165]
This is a bit of a "wild" idea, but something worth considering for the future. In a larger system with lots of users it is really convenient to externalize queries into files, although the facility exists to define queries through structured Rust, there is something to be said for being able to prototype in Kibana or Sense and then take copy the query for use in other projects, this proposal would see us have:

1) convenient method to load ES queries from files (say `myquery.es`), this is probably 3 lines of code of a good day, but might still make sense to have available to users.
2) template pre-processing of query strings, use a crate such as `tera` to process raw queries just before submission which allows: updating a timestamp, swapping out a term field, etc, etc. This works surprisingly well for use-cases where it makes more sense to have queries stored as strings (perhaps in files)

**Comment by KodrAus** [comment]
This shouldn't actually be too hard to plug in. `elastic_requests` uses a `Body` type that's just a wrapper around an owned or borrowed slice of bytes. Where those bytes come from doesn't matter. `json_str` is just one way.

You can also be abstract over any kind of request if you use the `HttpRequest` type, so you can avoid `SearchRequest` and friends.

So it should definitely be possible to seamlessly plug in some helpers for building requests from files.

**Comment by stephanbuys** [comment]
@KodrAus I've started work on the following crate: https://github.com/stephanbuys/elasticsearch-query.

Our web services rely on loading and manipulating queries (often prototyped in Kibana) from disk, which we then need to manipulate by adjusting filters, adding and removing aggregations, etc. I had a look at rs-es but it wasn't quite what I was looking for so I started rolling my own 'typed' and 'opinionated' ES query builder and manipulator.

Feedback/ideas/comments would be greatly appreciated. I envision that this might become another handy/optional component of your larger body of work.  Would be good to hear your thoughts on it.

Cheers!

**Comment by KodrAus** [comment]
Looking good! I'm glad to see a more strongly typed Query DSL underway. The fact that it's data-oriented means you could build a fluent API on top if you want, or maintain queries externally (like you're doing).

I'm really excited to see what direction you take this in.

**Comment by stephanbuys** [comment]
@KodrAus I have an initial working version up on https://github.com/stephanbuys/elasticsearch-query, feedback would be awesome.
Currently you can parse queries from JSON, construct them using builders, then also add filters and mess with the aggregation trees (insert, replace, remove aggregations).

**Comment by KodrAus** [comment]
@stephanbuys I'm really excited about this! Is the idea that other kinds of queries would be added to the `QueryField` structure?

**Comment by stephanbuys** [comment]
Hi yeah, some examples or pointers to what should be added (or pull requests) would be awesome. In time get to cover most of the API.

**Comment by stephanbuys** [comment]
@KodrAus I've added a sample of the lib working with async search from the `elastic` crate, also renamed to https://github.com/stephanbuys/elastic-queries

What would you like to see in the crate in order to eventually move it into elastic-rs (if interested :-) ) - in a sense it would be cool if it could live as an alpha/early crate in the elastic-rs organisation

**Comment by KodrAus** [comment]
Looks good! Sorry I haven't had a chance to really dig in yet and start contributing, but I definitely will.

You should feel welcome to add any crate in to the org here anytime :)

I think there are a few ways we could move this in to the org, depending on what you'd prefer. We could do any of:

- Add a new repo for `elastic-queries`, I think you should have access to set up travis-ci. Otherwise I'm happy to set that up. I don't think you'd need to worry about PRs or anything in a new repo, so if you're still planning a lot of churn this would be easy
- Add to the `/src` folder in this repo and include in the build here (this would be the best eventual destination)
- Add to a new root folder in this repo, like `/staging` or `/unstable` or something, so that everything in `/src` gets released in lock-step but everything in this new folder can evolve independently. I think this is a good solution so there's less infrastructure like CI to duplicate

For integration with `elastic` I'd like `queries` to eventually be a first-class thing. I intentionally called the method to add a raw body to a request `.body()` that so we've got room for `.query()` or something in the future to pass a strongly-typed query to directly.

It would also be neat to look at paramaterising queries over types in `elastic_types`, so if you create a range filter on a `date` field where we know the format is `epoch_millis` then we can serialise the range with the right format.

**Comment by stephanbuys** [comment]
I quite like the second suggestion, as a deep integration of the right parts makes a lot of sense (like what you mentioned around `epoch_millis` and `elastic_types` - I was starting to head in that direction here https://github.com/stephanbuys/elastic-queries/blob/master/src/filters/common.rs#L8 with a 'note to self' to go and see how you do that kind of thing in `elastic_types`). 
The biggest question would be how this affects your 'road to 1.x'; `queries` has a _lot_ of stuff missing...

**Comment by KodrAus** [comment]
> The biggest question would be how this affects your 'road to 1.x'; queries has a lot of stuff missing...

That's a good question. I think `1.0` is still a fair way off. We've got a hard dependency on `futures` and `tokio` reaching `1.0` as well as the `http` crate in the future. So I think there's plenty of room to play before that.

In `elastic_types` we use generic types for formatting dates and whatnot. So you'd have `EpochMillis::format` to get a date in the `epoch_millis` format. Introducing generics here would be tricky. Another option would be to erase the type with a `Box<DateFormat>` but the trait might not actually be object safe.

So I think we'll need to spend some time playing with it to find the best approach.

**Comment by stephanbuys** [comment]
Cool, I’ll prep a PR to get it merged into `src/` ?

**Comment by KodrAus** [comment]
Sounds good! Are you happy to keep working on `queries` in squashed PRs after the initial merge? You wouldn't need to wait for me to review them, but just to keep `master` green.

If you want to retain your original history from your repo then you can. For the other repos I just manually followed the steps from [a script on StackOverflow](https://stackoverflow.com/questions/13040958/merge-two-git-repositories-without-breaking-file-history/).

**Comment by KodrAus** [comment]
So we've got `queries` merged in here now and I think we can nut out integration with other crates here in separate issues so I'll close this one now.

Please feel free to re-open it if you'd like to keep it around @stephanbuys!
