### ISSUE TITLE
Make Client threadsafe

### ISSUE THREAD

**Issue by kardeiz** [elastic-rs/elastic#212]
`reqwest::Client` "holds a connection pool internally, so it is advised that you create one and reuse it".

It would be nice if `elastic::client::Client` could also be re-used (for example, as a static ref with `lazy_static`). The `headers` field of `elastic_reqwest::RequestParams` prevents one from doing so:

    `std::cell::UnsafeCell<std::option::Option<std::vec::Vec<std::vec::Vec<u8>>>>` cannot be shared between threads safely

It would be possible to work around this&mdash;I haven't thought about this very much, but the most naive approach would be to store raw header keys/values for `RequestParams` as owned strings or vecs, and then setting them back on the actual request.

Another workaround/compromise would be to provide an `elastic::client::Client` constructor that took both a `&reqwest::Client` and the `RequestParams`. That way the user could static-ify their client outside the `elastic` API. 

However, that also would require some non-trivial changes (making the client some kind of `Cow` or `Borrowed/Owned` enum, since the current `elastic::client::Client` owns its reqwest client).

**Comment by KodrAus** [comment]
You're right, the `Client` definitely needs to be thread-safe. It's also an issue if you construct a request and want to send it from another thread. Right now you can't do that. I think being able to pass a `reqwest::Client` in too is also a useful thing to do.

I'll have a look at `hyper`s raw header support, and if that removes the `UnsafeCell` then that'll be a good start.

We've got a story for adding a `ClientBuilder`, so one of the use cases I'll add for that is sharing a `Client` with `lazy_static`, and passing in your own `reqwest` client, probably as an `Arc<Client>`, since it doesn't need mutability to call.
