### ISSUE TITLE
Panic in index.rs example

### ISSUE THREAD

**Issue by outkaj** [elastic-rs/elastic#218]
Hello,

When running the index.rs example, I receive the following error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Response(Json(ErrorImpl { code: ExpectedSomeValue, line: 1, column: 1 })), State { next_error: None, backtrace: None })', /checkout/src/libcore/result.rs:860:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

The only change I have made to the example is adding the base URL for my own cluster using the base_url() function. 

I am using version 0.13.1 of elastic. 

I am happy to provide the full backtrace if it is helpful. 

Thanks for your time!

**Comment by KodrAus** [comment]
Hi @outkaj! It looks like the issue here is that the response we get back for the index request isn't a valid json object. That `Json(ErrorImpl { code: ExpectedSomeValue, line: 1, column: 1 })` error comes from `serde_json` when it expects a `{` character but gets something else. 

If you could add a full backtrace that would be really helpful so we know which operation is failing.

Thanks for being patient with this, I haven't really set up any debugging niceties yet (the client is still maturing) but logged #219 so we'll at least get better visibility of the raw request/responses in the future.

**Comment by outkaj** [comment]
Thank you for your quick reply!

Here is the full backtrace:

```
 0:      0x4dfc7c583b4 - backtrace::backtrace::libunwind::trace
                        at $HOMEDIR/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace<closure>
                        at $HOMEDIR/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/mod.rs:42
   1:      0x4dfc7c5878f - backtrace::capture::{{impl}}::new
                        at $HOMEDIR/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
   2:      0x4dfc7c4bf5c - error_chain::make_backtrace
                        at $HOMEDIR/.cargo/registry/src/github.com-1ecc6299db9ec823/error-chain-0.9.0/src/lib.rs:413
   3:      0x4dfc7c4c01f - error_chain::{{impl}}::default
                        at $HOMEDIR/.cargo/registry/src/github.com-1ecc6299db9ec823/error-chain-0.9.0/src/lib.rs:494
   4:      0x4dfc7c490fe - elastic::error::{{impl}}::from_kind
                        at $HOMEDIR/$PROJECTDIR/elastic-test-example/src/<error_chain_processed macros>:49
   5:      0x4dfc7c493d5 - elastic::error::{{impl}}::from
                        at $HOMEDIR/.cargo/registry/src/github.com-1ecc6299db9ec823/elastic-0.13.1/src/error.rs:46
   6:      0x4dfc7c42885 - core::convert::{{impl}}::into<elastic::error::ErrorKind,elastic::error::Error>
                        at /checkout/src/libcore/convert.rs:398
   7:      0x4dfc7c48580 - elastic::error::{{impl}}::from
                        at $HOMEDIR/.cargo/registry/src/github.com-1ecc6299db9ec823/elastic-0.13.1/src/error.rs:59
   8:      0x4dfc7c15aff - core::convert::{{impl}}::into<elastic_responses::error::ResponseError,elastic::error::Error>
                        at /checkout/src/libcore/convert.rs:398
   9:      0x4dfc7c0dec7 - core::ops::function::FnOnce::call_once<fn(elastic_responses::error::ResponseError) -> elastic::error::Error,(elastic_responses::error::ResponseError)>
                        at /checkout/src/libcore/ops/function.rs:143
  10:      0x4dfc7c0822d - core::result::{{impl}}::map_err<elastic_responses::command::CommandResponse,elastic_responses::error::ResponseError,elastic::error::Error,fn(elastic_responses::error::ResponseError) -> elastic::error::Error>
                        at /checkout/src/libcore/result.rs:487
  11:      0x4dfc7c2cd7d - elastic::client::responses::{{impl}}::into_response<elastic_responses::command::CommandResponse>
                        at $HOMEDIR/.cargo/registry/src/github.com-1ecc6299db9ec823/elastic-0.13.1/src/client/responses/mod.rs:114
  12:      0x4dfc7c2c044 - elastic::client::requests::create_index::{{impl}}::send<&[u8]>
                        at $HOMEDIR/.cargo/registry/src/github.com-1ecc6299db9ec823/elastic-0.13.1/src/client/requests/create_index.rs:132
  13:      0x4dfc7c3af93 - rs_es_elastic::main
                        at $HOMEDIR/$PROJECTDIR/elastic-test-example/src/main.rs:37
  14:      0x4dfc7e4eeec - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:98
  15:      0x4dfc7e4866b - std::panicking::try<(),closure>
                        at /checkout/src/libstd/panicking.rs:458
                         - std::panic::catch_unwind<closure,()>
                        at /checkout/src/libstd/panic.rs:361
                         - std::rt::lang_start
                        at /checkout/src/libstd/rt.rs:61
  16:      0x4dfc7c3bb52 - main
  17:     0x660b48f304c9 - __libc_start_main
  18:      0x4dfc7b8c119 - _start
  19:                0x0 - <unknown>) })', /checkout/src/libcore/result.rs:860:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
              at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:610
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:571
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:521
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:497
   8: core::panicking::panic_fmt
               at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
              at /checkout/src/libcore/macros.rs:31
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:738
  11: rs_es_elastic::main
             at ./main.rs:37
  12: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  13: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:458
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  14: main
  15: __libc_start_main
  16: _start
```

Also, I encountered a different error when trying to run the `typed.rs` example (similarly, the only modification I made was to the base URL). Should I file a separate issue for that and link it to #219? 

Thanks again.

**Comment by KodrAus** [comment]
Let's do that and see if they're related :+1:

So running locally against an Elasticsearch `5.4.1` node I'm not seeing any problems. I've opened a PR with some really basic logging that will tell us whether the request is actually failing and not being treated as an error or if there's some unexpected content encoding or something.

Do you mind pulling the branch for #220 down and giving that a go?

On another note I did notice the `index` sample won't actually work for multiple runs unless you delete the index first... I'll fix that up.

**Comment by outkaj** [comment]
My Elasticsearch node's version is `5.3.2`, if it's relevant. 

Thanks for your fast PR! As an update, I am still trying to find a way to test it on my system. 

If I specify the repo and branch in `Cargo.toml`, I receive the following error:  

```
error: failed to load source for a dependency on `elastic`

Caused by:
  Unable to update https://github.com/elastic-rs/elastic?branch=chore/logging

Caused by:
  failed to update submodule `benches/golang/src/github.com/chrisport/go-stopwatch`

Caused by:
  [17/-1] no URL configured for submodule 'benches/golang/src/github.com/chrisport/go-stopwatch'
```

If I clone the repository, add it to the local directory, and specify its location using the `[patch]` section of `Cargo.toml`, I receive this error instead:

```
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to load source for a dependency on `elastic`

Caused by:
  Unable to update file: HOMEDIR/PROJECTDIR/elastic-test-example/elastic
Caused by:
  found a virtual manifest at `HOMEDIR/PROJECTDIR/elastic-test-example/elastic/Cargo.toml` instead of a package manifest
```
(I see the `patch` feature is still in development, though, so this may not be surprising). 

Sorry for the lengthy comments and thanks again for your help!

**Comment by KodrAus** [comment]
That first issue is kind of weird, I've opened another PR #222 that should fix that. Once the build goes through I'll rebase the logging PR on that so you should be able to reference it by source in `Cargo.toml`.

That second issue is because the `Cargo.toml` in the root of the repo is actually just for a [workspace](https://doc.rust-lang.org/book/second-edition/ch14-03-cargo-workspaces.html) and doesn't have any source associated with it. That's bitten me a few times too, it would be nice if `cargo` could find its way from that workspace to the actual `Cargo.toml` and use that.

You should be able to fix that second issue by changing the path to `HOMEDIR/PROJECTDIR/elastic-test-example/elastic/elastic/Cargo.toml`.

**Comment by outkaj** [comment]
Referencing by source in `Cargo.toml` now works - thanks! And I'll keep in mind your tip regarding the second issue if I run into that problem again. 

I ran some tests with the new build, the output of which I saved in a gist [here](https://gist.github.com/outkaj/5aa83cf4be333956330896bdc7cee6e4) given the length. 

Interestingly, I notice Http Io Errors in both cases. Using the `client` from the `rs-es` library with my base URL to connect to my node is successful, but I still don't rule out some network misconfiguration or connection problem on my end. I'll let you know of the results of further tests/debugging on my part if relevant.

**Comment by KodrAus** [comment]
Hmm interesting. `rs-es` uses the http client `hyper` directly, but `elastic` uses a higher-level http client called `reqwest`, which sits on top of `hyper` and handles TLS and compression for you.

Is there a proxy in front of your node? Or does it require authentication?

If you set the `RUST_LOG` environment variable to `debug` you should see what HTTP status code you get back, and what headers. Are you getting `OK 200`s from them?

Otherwise if you're familiar with Wireshark on Linux or Fiddler on Windows you can also capture the whole request responses as they go through and see what content they have.

**Comment by KodrAus** [comment]
That `connection refused` error running with the default URL is expected, unless you're running an Elasticsearch node on `http://local host:9200`. I normally run it locally in a docker container for testing.

But thank you again for taking the time to look into this issue. There must be something about your environment that `elastic` should handle, but isn't, that's getting in the way. Maybe even as simple as getting a `401` back with a response body that isn't json.

**Comment by outkaj** [comment]
@KodrAus, thanks again for your help!

The cluster does have a username and password, which `rs-es` was able to parse from the URL. I think you are correct that the difference in http clients is causing the difference here. 

Confirming this, testing a minimal example with `reqwest` showed a 401 unauthorized error. I then specified the username and password explicitly (pulled from environment variables) [as detailed in the reqwest docs](https://docs.rs/reqwest/0.7.2/reqwest/struct.Url.html), but still receive the `401`. 

I'm going to keep debugging this, but you can probably close this issue, since it doesn't appear to be a bug in the example! Again, I really appreciate the time you took assisting me with this and how thoroughly you replied to all my questions. If I have thoughts as to #223, I will let you know.

**Comment by KodrAus** [comment]
Thanks for looping back @outkaj! I'll still keep improving logging and error messages in `elastic` so it's cleared in the future what's going on.

You can specify request headers, [see this example in the docs](https://docs.rs/elastic/0.13.2/elastic/index.html#creating-a-client), including authorisation but that's a bit clunky.

If `reqwest` by itself isn't behaving as you expect then it might be worth logging a bug there. The author is really helpful.

I'll make sure I'm not clobbering any auth details it might parse from the base url in `elastic`. We do set headers, so that might override what `reqwest` has. I'll open a new issue for making sure auth details are parsed from the base url.
