### ISSUE TITLE
Crashing failure in cernan 0.8.3 with elastic 0.20.6

### ISSUE THREAD

**Issue by blt** [elastic-rs/elastic#286]
The cernan project recently updated to `elastic` 0.20.6 in 0.8.3 and we're now getting reports of crashes in production. Example of the crash:

```[elastic::client::sync][71][2017-12-05T04:26:49.609229048+00:00][ERROR] Elasticsearch Response: correlation_id: '54dfed01-f59d-4c8d-95d0-2650b82dbecc', error: 'error sending a request or receiving a response. Caused by: error sending a request'
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Client(ClientError { inner: Error(Request, State { next_error: Some(Http(Error { kind: Io(Error { repr: Custom(Custom { kind: WouldBlock, error: StringError("timed out") }) }), url: Some("http://REDACTED.es.amazonaws.com/_bulk") })), backtrace: None }) })', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

It's unclear to me if the problem is internal to elastic or an issue with cernan's use of it. Our integration is here: https://github.com/postmates/cernan/blob/master/src/sink/elasticsearch.rs On further review I'm suspicious of the two unwraps present in this function: https://github.com/postmates/cernan/blob/master/src/sink/elasticsearch.rs#L176 but would appreciate any suggestions or other problematic uses of elastic. 

Cernan tracking issue: https://github.com/postmates/cernan/issues/353

**Comment by KodrAus** [comment]
Hi @blt, I'd say the issue would be that [second unwrap](https://github.com/postmates/cernan/blob/master/src/sink/elasticsearch.rs#L191) on the bulk call. The source appears to be [this error variant in `reqwest`](https://github.com/seanmonstar/reqwest/blob/master/src/error.rs#L316-L324). We get this when `reqwest`  fails to receive a response in the given timeout. It looks like along with the upgrade to `elastic 0.20` we also pulled in `reqwest 0.8` which introduces a default timeout of 30 seconds. It's possible that since these are bulk requests that 30 seconds just isn't long enough in this case (although that _is_ still a pretty long time) and the new default is being hit.

Right now the only way we'd expose that configuration would be through `reqwest` directly. You can build a `reqwest` client and pass it in to `elastic` with no timeout using its [`timeout` method](https://docs.rs/reqwest/0.8.1/reqwest/struct.ClientBuilder.html#method.timeout):

```rust
let http = reqwest::Client::builder()
    .timeout(None)
    .build()?;

let client = SyncClientBuilder::from_params(params)
    .http_client(http)
    .build()?;
```

But I think it would be good to add a convenient `timeout` method to `elastic`'s builder, that is ignored if you pass in a `http_client`.

**Comment by KodrAus** [comment]
Although if you're not expecting requests to ever take >30 seconds then it's possible the timeout is just the effect of some other problem.

If the user bumps the `RUST_LOG` environment variable up to `info` then starting requests will be logged too.

If there's anything else I can do to help please let me know!

**Comment by blt** [comment]
Hi @KodrAus, thank you for the quick response. I'll take care of that second unwrap and put cernan in a test environment, see how things go from there. I wouldn't expect requests to take > 30 seconds but anything can happen, I suppose.

An explicit timeout on `elastic`'s builder would be welcome.

**Comment by blt** [comment]
We've confirmed that postmates/cernan#356 resolves the problem. Thanks much!

**Comment by KodrAus** [comment]
No problem! Glad to hear it's working smoothly again. The timeout is potentially another error variant we could pull out to the top-level since it's another one you might reasonably want to respond to programmatically.
