### ISSUE TITLE
Is this project under development?

### ISSUE THREAD

**Issue by GopherJ** [elastic-rs/elastic#378]
Quick question: Is this project still under development? I posted actually two simple questions but no reply until now. If the reply may be slow, or if this project isn't under development, please add some information in README.md, thanks!

**Comment by KodrAus** [comment]
Hi @GopherJ :wave:

This project is currently only receiving sporadic attention from myself  because I have a lot of other commitments to keep up with, but have been working on getting it into a more contributable state for a while.

I'll try make some time to catch up on new issues. Thanks for your patience!

**Comment by mwilliammyers** [comment]
@GopherJ can I close this?
